language: node_js
cache: yarn

node_js:
  - "node"

before_script:
  - npm install -g gulp-cli

script: gulp --prod

matrix:
  fast_finish: true

deploy:
  skip_cleanup: true
  provider: npm
  email: $DEPLOY_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
