language: node_js
node_js:
  - "node"
  - "8"
before_script:
  - npm install -g gulp-cli

script: gulp --prod

matrix:
  fast_finish: true

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: travis-ci
